log_decorator.py            21 INFO      TestBalanceUnfrozenAfterTradeLessOrderPrice --> test_place_third_order
log_decorator.py            21 INFO      Order --> set_order
log_decorator.py            21 INFO      Calculator --> calculate_decimals
calculator.py               48 INFO     FLOAT
log_decorator.py            21 INFO      Calculator --> calculate_decimals
calculator.py               48 INFO     FLOAT
order.py                    67 INFO     Order was set to Order(type: 2, price: [pure-60, p_value-600, p_presc.-1], quantity: [pure-180, q_value-1800, q_presc.-1], order_id: , internal_id: 0, direction: 1, instrument_id: 1055, date_created: 2019-04-18), customer ID: 0, order status: , direction: 1,  filled quantity: 0, time in force: , transaction id: 
log_decorator.py            21 INFO      OrderService --> create_order
log_decorator.py            21 INFO      OrderServiceRequest --> create_order
log_decorator.py            21 INFO      Utils --> to_json
order_requests.py           59 INFO     Request body: {
    "jsonrpc": "2.0",
    "method": "OrderManagement.Create",
    "params": [
        {
            "order": {
                "direction": 1,
                "instrumentId": 1055,
                "orderType": 2,
                "price": {
                    "decimals": 1,
                    "value": 600
                },
                "quantity": {
                    "decimals": 1,
                    "value": 1800
                }
            }
        }
    ]
}
log_decorator.py            21 INFO      Utils --> to_json
order_service.py            26 INFO     Service Response: {'id': '', 'result': None, 'error': '{"type":2,"term":"balance_freezing.freezing validation.balance_freeze","details":"error freezing balance","incident_id":"656f45ad-420d-4cb9-8b37-1a1f738b769b"}'}
balance_unfrozen_after_trade_with_price_less_than_order_price_test.py   53 INFO     3 Order: {'id': '', 'result': None, 'error': '{"type":2,"term":"balance_freezing.freezing validation.balance_freeze","details":"error freezing balance","incident_id":"656f45ad-420d-4cb9-8b37-1a1f738b769b"}'}
log_decorator.py            26 CRITICAL test_place_third_order AssertionError automation_wrapper throws an exception: None
Traceback (most recent call last):
  File "C:\GitLab\platform-server_qa\src\base\log_decorator.py", line 22, in log_wrapper
    return func(*args, **kwargs)
  File "C:\GitLab\platform-server_qa\tests\web_platform_tests\trading_sanity_tests\balance_unfrozen_after_trade_with_price_less_than_order_price_test.py", line 54, in test_place_third_order
    assert order_response['error'] is None
AssertionError: assert '{"type":2,"term":"balance_freezing.freezing validation.balance_freeze","details":"error freezing balance","incident_id":"656f45ad-420d-4cb9-8b37-1a1f738b769b"}' is None